### PR TITLE
#31 Started building an order summary page for completed customer orders on back_end_experimental branch

### PR DESCRIPTION
**Pull request by VCastelli**
I started building the page for order summary after user completes their order. Will need Stefan's help to complete this page.

### CODE REVIEW

**Comment by gabrielkarras** [comment]
Why do you want to merge into main? We usually merge into testing first.

**Comment by gabrielkarras** [comment]
Also, letting you know that it failed to build...looks like something related to some detached commit from Minh. We'll look into it tomorrow.

**Comment by minhtrannhat** [comment]
> Also, letting you know that it failed to build...looks like something related to some detached commit from Minh. We'll look into it tomorrow.

This is a misconfiguration in the django.yml file. Github actions are set to run on push to branches and pull requests but the branch she tried to make the pull request from, backend experimental, is not in the list of branches that github actions would run on push commits. I will fix this soon.

**Comment by VCastelli** [comment]
> Why do you want to merge into main? We usually merge into testing first.

That was what I meant to do, but I think I selected the wrong branch to push to. Will fix this in the morning.

**Comment by VCastelli** [comment]
Code was reworked and pushed to back_end_experimental branch

**Pull request closed without merging**
