### PR TITLE
Feat: Added pre-commit hooks and Django template

### PR DESCRIPTION
**Pull request by minhtrannhat**
- Added Django template files. The server can now be started at port
  8000 by running `python manage.py runserver`.
- Added pre-commit hooks for checking code quality before commiting.

### CODE REVIEW

**Comment by minhtrannhat** [comment]
I can confirm that this setup works on all three systems that I have tested: Linux, Windows 10 and MacOS

**Comment by minhtrannhat** [comment]
This is safe to merge now. Thank you.

**Comment by gabrielkarras** [comment]
I'm not familiar with the .toml? Would you mind explaining?

**Comment by minhtrannhat** [comment]
Yeah sorry about that,  I should have made it clearer. So there is this tool that runs everytime you commit called "black", it is a code formatter: https://github.com/psf/black. And it requires a configuration that lives in the pyproject.toml file. Hope this helps !

**Comment by gabrielkarras** [comment]
Looks fantastic! I'll post the link on our Discord. Otherwise, no issues to declare.

**Review by gabrielkarras — APPROVED** [review]

**Comment by minhtrannhat** [comment]
Thanks for doing the review !

**Pull request merged**
