### PR TITLE
Include Django-React REST Framework and React to Project

### PR DESCRIPTION
**Pull request by gabrielkarras**
I grabbed Minh's latest branch(#38,#64) and included React to the project as well as setting up the Django REST framework.
Folders have been renamed to backend(for main DJango app), frontend(React app) and model_api(Django app for our DB models).

### CODE REVIEW

**Review by minhtrannhat — COMMENTED** [review]
Can you merge the content of the `.gitignore` file in the frontend folder into the `.gitignore` in the root of this repo ? I think this `.gitignore` is a little redundant.

**Comment by gabrielkarras** [comment]
@minhtrannhat Done!

**Review by minhtrannhat — COMMENTED** [review]
What is the purpose of `model_api` and `model-api` folders?

**Comment by gabrielkarras** [comment]
OH! Wth! I completely missed that. Thanks for catching I'll remove "model-api"

**Comment by gabrielkarras** [comment]
Removed and passed CI.

**Comment by minhtrannhat** [comment]
Awesome ! Thank you !

**Comment by minhtrannhat** [comment]
All code tested ! It's good to merge now.

**Review by minhtrannhat — APPROVED** [review]
Code reviewed

**Pull request merged**
